MVC_C#_Projects/MVC_Project2021/Controllers/ProductController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using MVC_Project2021.Data;
using MVC_Project2021.Models;
using MVC_Project2021.ViewModels;
using System;
using System.IO;
using System.Linq;

namespace MVC_Project2021.Controllers
{
    public class ProductController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly IWebHostEnvironment hostingEnvironment;

        public ProductController(ApplicationDbContext db, IWebHostEnvironment hostingEnvironment)
        {
            _db = db;
            this.hostingEnvironment = hostingEnvironment;
        }

        public IActionResult Index(string searchBy, string search)
        {
                if (searchBy == "Product Code")
                {
                    return View(_db.Product.Where(x => x.ProductCode.Contains(search) || search == null).ToList());
                }
                else
                {
                    return View(_db.Product.Where(x => x.ProductName.Contains(search) || search == null).ToList());
                }
        }

        //Get - Create
        public IActionResult Create()
        {

            return View();
        }
        //Post - Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ProductCreateViewModel obj)
        {
            if (ModelState.IsValid)
            {
                string uniqueFileName = ProcessUploadedFile(obj);

                Product newProduct = new Product
                {
                    ProductCode = obj.ProductCode,
                    ProductName = obj.ProductName,
                    ProductPrice = obj.ProductPrice,
                    ProductImage = uniqueFileName

                };
                _db.Product.Add(newProduct);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);            
        }

        //Get - Edit
        [HttpGet]
        public IActionResult Edit(int? id)
        {
            if(id == null|| id == 0)
            {
                return NotFound();
            }
            var obj = _db.Product.Find(id);
            if(obj != null)
            { 
                ProductEditViewModel productEditViewModel = new ProductEditViewModel
                {
                    Id = obj.Id,
                    ProductCode = obj.ProductCode,
                    ProductName = obj.ProductName,
                    ProductPrice = obj.ProductPrice,
                    ExistingImagePath = obj.ProductImage
                };
                return View(productEditViewModel);
            }
            return NotFound();
        }
        //Post - Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditPost(ProductEditViewModel obj)
        {
            if (ModelState.IsValid)
            {

                Product product = _db.Product.Find(obj.Id);
                product.ProductCode = obj.ProductCode;
                product.ProductName = obj.ProductName;
                product.ProductPrice = obj.ProductPrice;

                if (obj.ProductImage != null)
                {
                    product.ProductImage = ProcessUploadedFile(obj);
                } 

                _db.Product.Update(product);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        private string ProcessUploadedFile(ProductCreateViewModel obj)
        {
            string uniqueFileName = null;
            if (obj.ProductImage != null)
            {
                string uploadsFolder = Path.Combine(hostingEnvironment.WebRootPath, "lib\\img");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + obj.ProductImage.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);

                obj.ProductImage.CopyTo(new FileStream(filePath, FileMode.Create));
            }
            return uniqueFileName;
        }

        //Get - Delete
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var obj = _db.Product.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            ProductEditViewModel productEditViewModel = new ProductEditViewModel
            {
                Id = obj.Id,
                ProductCode = obj.ProductCode,
                ProductName = obj.ProductName,
                ProductPrice = obj.ProductPrice,
                ExistingImagePath = obj.ProductImage
            };
            return View(productEditViewModel);
        }
        //Post - Delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var obj = _db.Product.Find(id);
            if (obj != null)
            {
                _db.Product.Remove(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }    
            return NotFound();
        }
    }
}

MVC_C#_Projects/MVC_Project2021/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using MVC_Project2021.Data;
using MVC_Project2021.Models;
using System.Linq;

namespace MVC_Project2021.Controllers
{
    public class UserController : Controller
    {
        private readonly ApplicationDbContext _db;

        public UserController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index(string searchBy, string search)
        {
            if (searchBy == "Username")
            {
                return View(_db.User.Where(x => x.Username.Contains(search) || search == null).ToList());
            }
            else if (searchBy == "Fullname")
            {
                return View(_db.User.Where(x => x.Fullname.Contains(search) || search == null).ToList());
            }
            else
            {
                return View(_db.User.Where(x => x.Email.Contains(search) || search == null).ToList());
            }
        }

        //Get - Create
        public IActionResult Signup()
        {

            return View();
        }
        //Post - Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult SignupPost(User obj)
        {
            if (ModelState.IsValid)
            {
                _db.User.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }
        //Get - Edit
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var obj = _db.User.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }
        //Post - Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditPost(User obj)
        {
            if (ModelState.IsValid)
            {
                _db.User.Update(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }
        //Get - EditPassword
        public IActionResult EditPassword(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var obj = _db.User.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }
        //Post - EditPassword
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditPasswordPost(User obj)
        {
                if (ModelState.IsValid)
                {
                    _db.User.Update(obj);
                    _db.SaveChanges();
                    return RedirectToAction("Index");
                }
            return View(obj);
        }
    }
}

MVC_C#_Projects/MVC_Project2021/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewData["Title"] - MVC_Project2021</title>

    <link rel="shortcut icon" href="~/lib/img/cool3.jpg" type="image/x-icon" />
    <link rel="apple-touch-icon" href="~/lib/img/cool3.jpg" />

    <!-- imported bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- local library -->
    <link rel="stylesheet" href="~/lib/css/bootstrap.min.css" type="text/css" />
    <link rel="stylesheet" href="~/lib/css/styles.css" type="text/css" />
    <link rel="stylesheet" href="~/lib/css/font-awesome.min.css" type="text/css" />
</head>
<body>
    <div class="wholebody">
        <div id="header">
        </div><!-- end header -->
        <div class="menu-wrapper">
            <div class="mobile-menu">
                <nav class="navbar navbar-inverse">
                    <div class="container-fluid">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar" aria-label="Toggle navigation">
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                        </div>
                        <div id="navbar" class="navbar-collapse collapse">
                            <ul class="nav navbar-nav">
                                <li class="dropdown">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                                </li>
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> Data Listing <span class="fa fa-angle-down"></span></a>
                                    <ul class="dropdown-menu">
                                        <li><a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Users</a></li>
                                        <li><a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Products</a></li>
                                    </ul>
                                </li>
                                @*<li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> Banner Slider <span class="fa fa-angle-down"></span></a>
                                    <ul class="dropdown-menu">
                                        <li><a class="nav-link text-dark" asp-area="" asp-controller="BannerSlider" asp-action="Index">Manage Slider</a></li>
                                    </ul>
                                </li>*@
                            </ul>
                        </div><!--/navbar-collapse -->
                    </div><!--/.container-fluid -->
                </nav>
            </div><!-- end mobile-menu -->
            <header class="vertical-header">
                <div class="vertical-header-wrapper">
                    <nav class="nav-menu">
                        <ul class="primary-menu">
                            <li class="child-menu dropdown">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="child-menu dropdown">
                                <a href="#" class="dropdown-toggle collapsed" data-toggle="collapse" data-target="#collapse1" role="button" aria-expanded="false" aria-controls="collapse1">
                                    Data Listing
                                    <span class="fa fa-angle-down"></span>
                                </a>
                                <ul id="collapse1" class="sub-menu collapse">
                                    <li><a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Users</a></li>
                                    <li><a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Products</a></li>
                                </ul>
                            </li>
                            @*<li class="child-menu dropdown">
                                <a href="#" class="dropdown-toggle collapsed" data-toggle="collapse" data-target="#collapse2" role="button" aria-expanded="false" aria-controls="collapse2">
                                    Banner Slider
                                    <span class="fa fa-angle-down"></span>
                                </a>
                                <ul id="collapse2" class="sub-menu collapse">
                                    <li><a class="nav-link text-dark" asp-area="" asp-controller="BannerSlider" asp-action="Index">Manage Slider</a></li>
                                </ul>
                            </li>*@
                        </ul>
                    </nav><!-- end nav-menu -->
                </div><!-- end vertical-header-wrapper -->
            </header><!-- end header -->
        </div><!-- end menu-wrapper -->
        <div id="main" class="right">
            <div id="content" class="container-fluid">
                @RenderBody()
            </div>
        </div>
            <div id="footer">
                <h2 class="text-center text-muted col-lg-offset-2"><small>MVC Project 2021</small></h2>
            </div><!-- end footer -->
        </div><!-- end whole body -->

    <script src="~/lib/js/jquery.min.js"></script>
    <script src="~/lib/js/bootstrap.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>